# Generated by Django 4.0.5 on 2022-06-06 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_alter_message_receiver_alter_message_sender'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='messages',
            field=models.ManyToManyField(to='mainapp.message'),
        ),
    ]
